version: "3.3"
services:
  web:
    image: danceschool_web:latest
    deploy:
      replicas: 1
    env_file: 
      - env.default
      - env.web
    volumes:
      - staticfiles:/data/web/school/staticfiles
      - media:/data/web/school/media
      - private_media:/data/web/school/smedia
      - ./backups/web:/backup
      - ./custom:/data/web/custom
    secrets:
      - postgres_url
      - django_secret_key
    working_dir: /data/web
    command: gunicorn school.wsgi:application -w 2 -b :8000
    networks:
      danceschool_default:
        aliases:
          - web
    depends_on:
      - postgres

  nginx:
    image: danceschool_nginx:latest
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - staticfiles:/data/web/staticfiles
      - media:/data/web/media
    networks:
      danceschool_default:
        aliases:
          - nginx
    depends_on:
      - web

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx
    networks:
      danceschool_default:
        aliases:
          - letsencrypt
    depends_on:
      - nginx

  postgres:
    image: postgres:10.6
    hostname: postgres
    deploy:
      replicas: 1
    volumes:
      - ./backups/postgresql:/backup
      - postgres:/var/lib/postgresql/data
    env_file: env.default
    networks:
      danceschool_default:
        aliases:
          - postgres

  redis:
    image: redis:latest
    hostname: redis
    deploy:
      replicas: 1
    networks:
      danceschool_default:
        aliases:
          - redis 

  huey:
    image: danceschool_web:latest
    deploy:
      replicas: 1
    env_file: 
     - env.default
     - env.web
    secrets:
      - postgres_url
      - django_secret_key
    volumes:
      - staticfiles:/data/web/school/staticfiles
      - media:/data/web/school/media
      - private_media:/data/web/school/smedia
      - ./backups/web:/backup
      - ./custom:/data/web/custom
    working_dir: /data/web
    command: python3 manage.py run_huey
    networks:
      danceschool_default:
        aliases:
          - huey
    depends_on:
      - postgres
 
volumes:
  postgres:
    external:
      name: danceschool_postgres
  staticfiles:
    external:
      name: danceschool_staticfiles
  media:
    external:
      name: danceschool_media
  private_media:
    external:
      name: danceschool_privatemedia
  certs:
    external:
      name: danceschool_certs
  vhost.d:
    external:
      name: danceschool_vhost.d
  html:
    external:
      name: danceschool_html

networks:
  danceschool_default:
    driver: overlay

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_url:
    external: true
  django_secret_key:
    external: true